spring.application.name=api
server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update

spring.data.mongodb.uri=mongodb://root:secret@localhost:27017/mydatabase?authSource=admin